export const ELEMENT = {
  SEARCH_FORM: document.querySelector(".search"),
  SEARCH_BTN: document.querySelector(".search-btn"),
  INPUT: document.querySelector(".input"),
  DEGREE: document.querySelector(".info-degree"),
  INFO_IMG: document.querySelector(".info-img"),
  CITYS: document.querySelector(".citys"),
  LIKE_IMG: document.querySelector(".info-footer__img"),
  TEMP: document.querySelector(".temperature"),
  FEELS: document.querySelector(".feels"),
  WEATHER: document.querySelector(".weather"),
  SUNRISE: document.querySelector(".sunrise"),
  SUNSET: document.querySelector(".sunset"),
  LIST: document.querySelector(".forecast__card_list"),
  CITY_NAME: document.querySelector(".city-name"),
};
