export const ELEMENT = {
  SEARCH_FORM: document.querySelector(".search"),
  SEARCH_BTN: document.querySelector(".search-btn"),
  INPUT: document.querySelector(".input"),
  DEGREE: document.querySelector(".info-degree"),
  INFO_IMG: document.querySelector(".info-img"),
  CITYS: document.querySelector(".citys"),
  LIKE_IMG: document.querySelector(".info-footer__img"),
  CITY_NAME: document.querySelector(".city-name"),
  TEMP: document.querySelector(".temperature"),
  FEELS: document.querySelector(".feels"),
  WEATHER: document.querySelector(".weather"),
  SUNRISE: document.querySelector(".sunrise"),
  SUNSET: document.querySelector(".sunset"),
  LIST: document.querySelector(".forecast__card_list"),
};

export const MONTH = {
  0: "January",
  1: "February",
  2: "March",
  3: "April",
  4: "May",
  5: "June",
  6: "July",
  7: "August",
  8: "September",
  9: "October",
  10: "November",
  11: "December",
};
